<?php

namespace Vanguard\Http\Requests\Member;

use Illuminate\Foundation\Http\FormRequest;

class MemberRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'email' => 'required|email|unique:members,email',
            'username' => 'required|unique:members,username',
            'password' => 'required|confirmed|min:8',
        ];

    }

    public function messages()
    {
        return [
            'email.required' => 'Please, Input a valid Email address',
            'username' => 'Username required',
            'password' => 'Minimum 8 Characters',
        ];
//        return parent::messages(); // TODO: Change the autogenerated stub
    }
}
